<a href="https://colab.research.google.com/github/idrees006/DecodeLabs-Internship/blob/main/Multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORT LIBRARIES

In [29]:
import pandas as pd
import numpy as np

import sklearn
import sklearn.datasets as datasets

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn.metrics as metrics

import matplotlib.pyplot as plt
from matplotlib import style
style.use('dark_background')

# CREATING DATA USING SKLEARN

In [30]:
data = datasets.make_regression(n_samples = 1000,   # no of samples
                                n_features = 3,     # no of features
                                n_informative = 3,  # no of usefull features

                                #random_state = 42   # no of same datapoint on each run
                                )

In [31]:
type(data)

tuple

In [32]:
len(data)

2

In [33]:
data

(array([[ 0.14000933, -0.05431813,  0.17998741],
        [ 1.10182046, -0.87081727, -1.00542591],
        [ 0.2517129 ,  0.52562564, -0.70334619],
        ...,
        [ 0.62277559, -0.37504158, -1.27352294],
        [ 2.18771222, -0.70100731,  1.96876179],
        [-0.51319481, -1.11554337, -0.49791755]]),
 array([ 1.76521073e+01, -3.86626127e+01,  2.69869840e+00,  3.83737933e+01,
        -5.90274571e+01, -7.30768595e+01,  1.12083058e+02, -7.05306383e+01,
         2.32833470e+00, -2.21662380e+01,  7.58491375e+01, -1.62193316e+02,
        -1.58353923e+01, -1.32012268e+02, -6.46348381e+01, -7.58868405e+00,
         9.74578756e+01,  1.04645046e+02, -2.74244836e+01,  2.54646726e+01,
        -7.77558058e+01, -1.81852095e+02,  1.38926347e+02,  5.00482784e+01,
         6.74253839e+01,  2.07384154e+02,  2.75955808e+01,  4.93479467e+01,
         4.35423796e+01, -1.53903959e+02,  2.46444558e+01, -2.49105558e+01,
        -1.24680342e+02, -1.83518717e+01,  1.23756131e+02, -6.99284014e+00,
        -5.20616339e+01,  1.03207366e+02,  1.44530183e+01, -7.81259985e+01,
        -1.77530755e+02, -3.44155415e+01, -5.34576019e+01,  1.35698585e+02,
        -1.12700214e+02, -3.71827948e+01, -2.43786216e+01, -1.44762021e+02,
        -1.31599841e+02,  2.24253971e+02,  1.05071186e+02, -3.01923846e+01,
        -6.93869013e+01,  1.79460403e+01,  4.22585640e+01, -3.23054100e+01,
         9.13398741e+01,  1.47756423e+01,  5.56348570e+01, -1.61094419e+02,
        -7.85477525e+01,  1.84077107e+02,  1.18643234e+02,  2.14827312e+01,
        -5.60436957e+01,  1.51890881e+02,  1.23109978e+02,  3.55768661e+01,
        -1.35099777e+02,  2.43753645e+01,  2.42860907e+02, -2.23396689e+02,
        -6.90004844e+01,  1.89772712e+02, -1.55378915e+02,  8.39761266e+01,
         2.56946563e+01, -5.75553527e+01, -5.76038168e+01,  2.22461500e+01,
        -2.29138312e+01, -5.26080733e+01,  7.71908413e+01, -9.14835855e+01,
        -1.90478988e+02, -4.44331435e+01,  2.69155413e+01,  4.06399224e+01,
         9.47282150e-01, -3.65829659e+01, -1.74752167e+01, -6.10359030e+01,
         1.18214797e+01, -1.71376536e+02,  1.18957234e+02, -4.42701800e+01,
         7.27169045e+01, -2.68259622e+02, -2.04132160e+02, -5.70307865e+01,
         2.44059475e+02,  9.48450081e+01,  1.48678108e+02, -9.98404865e+01,
         1.23815207e+02, -7.33122978e+01, -6.78417151e+01, -8.62477491e+01,
         3.94496030e+01, -3.02669440e+01,  9.32546938e+01, -1.81772598e+00,
        -1.40815363e+02, -1.64711386e+02, -8.21125242e+01, -9.06320124e+01,
        -1.08776224e+01,  2.24837123e+01, -1.81578137e+02,  7.64969181e+01,
         1.62306259e+00, -1.78076235e+02, -1.46201344e+02,  9.36053832e+01,
         2.11356607e+02, -2.48587994e+00,  2.91576253e+01,  7.67135923e+01,
        -1.89179356e+01,  7.80446912e+01, -3.63095267e+01, -6.64944420e+01,
        -1.75102826e+01, -5.56556908e+01, -1.21727046e+02, -9.83989970e+01,
        -1.31825557e+02, -3.54906068e+01, -7.15556003e+01,  7.26966050e+01,
         7.71960590e+01, -6.25076351e+01, -6.03436824e+01, -2.04665355e+02,
        -3.07357264e+01,  1.80853606e+02,  8.95785336e+01, -2.36998882e+01,
        -5.42645518e+00,  1.19893403e+02, -1.46415456e+01, -8.12355385e+01,
        -6.60328995e+01,  7.41949864e+01, -1.01988297e+02, -1.75919276e+02,
         1.91695669e+02, -7.63289468e+01, -1.16206919e+02, -1.57342442e+02,
         1.95012530e+02, -9.82502811e+01, -1.12173567e+02,  1.30647112e+02,
        -4.92908871e+00,  9.04348666e+01,  3.11950711e+01,  3.98746562e+01,
        -7.50169198e+01, -1.19110154e+01, -2.11614020e+02,  1.71632695e+01,
         1.57492478e+01,  9.64643191e+01,  2.11997324e+02, -1.04053028e+01,
         1.72757856e+02,  6.31134545e+01, -7.06290120e+01, -2.44023055e+01,
        -1.11367435e+02, -3.41521628e+01, -5.73368236e+01, -9.84922231e+01,
        -1.56361708e+02, -1.03670666e+02, -8.59351805e+00,  7.37759707e+01,
         9.59563166e+01,  7.59438600e+01,  1.80036641e+01,  6.76790065e+01,
         5.90822196e+01,  6.08902379e+01,  7.87882383e+01, -1.92035020e+02,
        -9.53674296e+01, -9.35111573e+01,  3.87918259e+01, -2.31058990e+02,
        -1.31708715e+02, -1.69107013e+02, -1.05103748e+02,  2.44180162e+02,
        -2.29926853e+01, -1.42100535e+02,  3.48942153e+01,  2.13360253e+02,
         9.26202523e+01,  9.76296929e+01, -1.17310693e+01, -8.46131912e+01,
         1.28864087e+02, -1.36834932e+02, -1.19167350e+02,  1.90171432e+02,
         5.53546928e+01, -1.43800503e+02,  1.00074543e+02, -3.30647622e+00,
        -7.33577420e+01,  1.15699654e+02,  2.23191567e+02,  1.42304385e+02,
         3.51385987e+01,  1.30307417e+02, -2.78193575e+01,  2.01610677e+02,
        -1.82972810e+02, -1.96011755e+01,  2.73150593e-01, -5.21350306e+01,
        -1.00557686e+02, -2.10693381e+02, -9.93966243e+00,  1.54460738e+01,
         5.31408493e+01, -3.58388634e+01, -5.70706963e+01, -6.58420108e+01,
         3.84246312e+01, -9.49989625e+01, -4.96825176e+01,  6.33462289e+01,
         9.86010102e+01,  6.28701524e+01,  3.32334192e+02, -7.97989594e+01,
        -1.08225282e+02, -1.85890928e+02,  2.16602416e+01, -1.01501257e+02,
         1.05326463e+02, -4.11750605e+01,  1.61680297e+02,  1.45833945e+02,
         1.90237877e+01, -1.89752067e+02,  3.11037289e+01, -1.15322632e+01,
         1.40886695e+02, -7.45229054e+01, -1.59343443e+02, -4.80576633e+00,
         8.34521888e+01,  8.42290253e+01, -6.80439221e+01,  9.12077404e+01,
        -1.52354571e+01, -8.40260084e+01,  6.09544159e+01,  2.02106504e+01,
        -8.11963358e+01, -7.29430069e+01,  2.11201519e+02,  2.66641431e+01,
         5.54440985e+01,  5.04286700e+00,  1.37736791e+02,  8.36839241e+01,
         1.35742811e+01, -1.36363956e+02,  1.40213301e+01,  1.18760601e+02,
         8.04841232e+00, -1.48423396e+01, -3.53365267e+01,  2.34178639e+01,
        -7.84102194e+01,  6.97079536e+01,  5.16658259e+01,  1.10859269e+02,
         1.39686913e+02, -1.68369384e+02, -1.90676812e+02,  1.30537798e+02,
         1.23175765e+02, -2.02991566e+02, -1.65889951e+02, -1.59824085e+02,
         8.24174380e+01, -1.04772047e+02,  1.28202862e+02,  7.39516882e+01,
         1.15207156e+01, -3.93132074e+01, -4.08600913e+01,  1.07403050e+02,
         2.17571350e+01,  1.12405671e+02,  6.03088988e+01, -5.19047001e+00,
         8.84453402e+00,  9.40450324e+01,  1.61645770e+02,  5.04671336e+01,
         4.92910814e+01, -9.65575601e+01, -1.57360831e+02,  1.03964036e+02,
         1.45632566e+02, -4.38547833e+01, -6.98433640e+01, -3.99559562e+01,
        -1.48062379e+02,  8.50609870e+01,  9.43912773e+01, -1.58150383e+02,
        -1.54422942e+02, -9.89359481e+01,  1.04772562e+02,  2.61467512e+01,
        -1.06882349e+02, -2.98308160e+01,  7.90714115e+01, -6.58121292e+01,
         2.80867865e+01,  6.71264438e+01, -5.18521802e+01, -4.36268296e+01,
         3.72060436e+01,  9.75401233e+01,  2.77964137e+02, -2.80254139e+00,
         5.42728622e+01, -5.20969522e+01,  8.60793231e+01, -1.36767704e+00,
         8.15381413e+01, -7.16276541e+01, -1.42808538e+00,  1.92849018e+01,
        -3.09188359e+01, -1.22370274e+02,  1.53826210e+02, -1.35348987e+02,
        -2.31386034e+02,  2.37492858e+01,  5.01517961e+01, -6.40315969e+01,
         1.39778178e+02,  1.64172843e+02, -6.86716679e+01,  9.70055802e+01,
        -6.15824707e+00,  5.72792522e+01,  7.43971182e+01,  3.01271419e+01,
        -1.98405299e+00, -4.12896035e+01, -2.33778661e+01,  1.61463978e+01,
         3.44890855e+01, -3.34580218e+02, -8.53128481e+01,  7.83005598e+01,
        -1.24924157e+02,  2.40165588e+02, -1.01624486e+02, -1.30430616e+02,
         2.76639820e+01, -5.88354103e+01, -1.27297303e+01,  1.39514391e+02,
        -2.44912658e+01,  4.64456269e+00, -3.73663089e+01, -7.24580027e+01,
         1.43218676e+02,  8.78040857e+01,  3.49200438e+00, -1.80725500e+02,
        -3.66808637e+01,  1.17778604e+02,  1.62304140e+02, -1.49864681e+02,
         4.74856132e+01, -6.07922708e+01, -4.45400888e+01,  3.46265814e+01,
        -1.21527352e+02,  2.83053945e+00,  2.71925812e+02, -2.16245347e+01,
        -1.04242270e+02,  3.70438349e+01, -8.83271842e+01,  3.05844546e+02,
        -2.01391492e+02, -8.24444006e+01, -1.33124048e+02,  2.25155520e+01,
        -3.08645378e+02,  1.03074965e+02,  1.73389723e+02,  8.10767655e+00,
        -1.05892974e+02, -8.04781625e+01, -1.39558361e+02, -3.68576369e+01,
        -1.39879020e+02,  7.84358407e+01,  1.34929917e+01, -2.26094475e+02,
         8.77523397e+01,  6.06072961e-01, -9.43487218e+00,  3.54422137e+01,
        -1.03136451e+02,  1.28587222e+02,  3.42547584e+01,  4.15429792e-01,
         1.56706946e+02,  1.07537869e+02, -5.22151933e+01,  1.46660939e+02,
         2.35253481e+02,  1.43090195e+02, -2.87559807e+02, -3.70331299e+01,
         1.43089783e+02,  1.37472759e+02, -1.63302609e+02,  5.32961148e+01,
        -1.31334189e+02,  1.84627871e+01,  1.81216196e+02, -3.30323496e+01,
         2.00999262e+00,  3.60310751e+01,  1.18151977e+01,  8.01899747e+01,
        -1.11077387e+02, -1.40174093e+01, -4.10849402e+01,  2.95236366e+01,
         1.04858476e+02, -5.04635345e+01,  1.60194230e+02,  3.59643559e+01,
        -1.56941937e+01,  3.04696211e+00,  1.14288322e+02, -2.30183516e+02,
        -9.16773628e+01, -1.60851265e+01, -9.47450456e+01, -1.31943251e+02,
         8.46202155e+01,  2.04178461e+02, -1.14579356e+02, -2.01135373e+02,
         2.92769872e+00, -1.03325133e+02, -6.77010155e+01,  9.44434198e-01,
        -8.85140140e+01,  1.55887707e+02,  6.43485302e+01, -3.10281318e+01,
         7.97747618e+01, -9.58903472e+01, -1.10294659e+02,  1.88269258e+01,
         1.59647256e+02, -6.69435157e+01,  2.85752131e+00, -1.11777655e+01,
        -1.08779465e+02,  3.43325086e+01, -5.74021433e+01,  1.19685285e+02,
         1.47935325e+01, -1.92339805e+01, -1.47381428e+02,  1.29230509e+02,
         1.00657697e+02, -1.76474345e+00,  9.36248837e+01,  2.89029989e+00,
        -1.00512371e+02, -6.88913924e+01,  2.51039419e+01,  4.91180226e+01,
         1.02459874e+02, -4.41068756e+01, -1.05746393e+02,  5.23648998e+01,
         1.84754241e+00, -2.18950081e+02,  1.38032299e+01,  7.33674869e+01,
        -6.15957818e+01, -8.76941672e+00,  2.74494904e+02,  1.82246579e+02,
         3.00885747e+02, -1.30018792e+02,  2.44297785e+02, -1.14798267e+01,
        -1.25200617e+02,  2.12059346e+02,  1.91418517e+01, -7.11527284e+01,
        -5.44465212e+01,  2.22071817e+01, -3.22047074e+01, -2.52804369e+02,
         1.68366382e+02, -2.53882644e+01, -1.20574901e+02, -5.08674068e+01,
        -8.53323850e+01, -1.05395653e+01, -1.44961617e+02,  1.79455278e+01,
         1.00285806e+02,  5.99629052e+01,  1.77239328e+02, -1.48244718e+02,
        -6.34092852e+01,  3.87737324e+00, -1.50137675e+02,  2.11842614e+01,
         2.06431518e+02, -2.39372993e+02,  1.01046621e+02,  1.56466796e+01,
        -1.30142637e+02,  7.25762682e-01,  2.20743852e+01,  9.92435383e+01,
        -4.94019759e+01, -4.92240471e+01,  3.07894945e+01,  5.65610319e+01,
        -8.31896042e+00,  7.02102363e+00, -1.47457466e+01,  1.90560172e+02,
         2.21469308e+02,  2.42604693e+02, -1.06895510e+02, -5.16028829e+01,
        -6.52224514e+01,  2.12797475e+02,  1.15548290e+02, -3.78658464e+00,
         3.71151517e+01, -1.48413499e+02, -1.67614583e+02, -9.53227077e+01,
        -1.28677354e+02, -1.31291051e+02,  2.48106103e+01,  6.57594905e+01,
         1.37624098e+02,  8.00834154e+01, -8.52550134e+01, -1.24013667e+02,
         5.15528559e+01, -2.25230746e+02,  5.27977185e+01, -9.29342462e+01,
        -8.05163729e+01,  1.15400400e+02, -1.18224137e+02,  1.56853899e+02,
         1.67821841e+01,  4.87690049e+01, -6.55958902e+01, -4.20464414e+01,
         7.05450785e+01,  7.97659458e+01,  1.07433406e+02,  1.46863176e+02,
        -1.89001302e+01, -1.17866673e+02,  2.42607702e+01, -1.79419786e+01,
         7.86027339e+01,  7.87249293e+01,  4.02496730e+01,  1.33054845e+02,
         3.32788685e+01, -1.14441344e+02,  8.98620947e+01,  1.64498539e+02,
        -4.80201176e+01, -6.87907224e+01, -1.77165614e+01, -1.84425093e+01,
         1.41115853e+02,  1.44515773e+02, -1.79787469e+01, -5.59164608e+01,
         1.22403001e+02, -8.31147867e+01,  6.26969337e+01,  1.39560766e+02,
         4.69729013e+01, -6.71660764e+00, -1.46257455e+02, -2.55245193e+01,
        -1.71359269e+01,  1.45654729e+00, -2.47458031e+02,  1.06187384e+02,
        -1.11110427e+02, -3.94882872e+01,  2.70043384e+02, -3.01304895e+01,
        -2.30824555e+01, -1.52445401e+02,  1.21093800e+02, -4.58604669e+00,
        -1.47525614e+02,  1.65114896e+02,  4.29322426e+01, -6.38611204e+00,
        -1.04899009e+02,  2.73262972e+01, -2.77725251e+01,  4.43080220e+00,
         1.69550016e+02, -1.40579055e+01,  1.50159743e+02,  1.33392827e+02,
        -4.83972958e+01, -1.28120147e+02,  1.04473963e+02, -5.14183875e+01,
         3.06720133e+01,  1.18728032e+02,  8.27160553e+01, -9.12618882e+01,
         4.64589269e+00, -1.34759167e+02,  7.66330808e+01,  7.03551243e+01,
        -5.22644919e+01, -1.87166713e+02,  5.06333766e+01, -9.88541668e+00,
        -1.88141573e+02,  3.38152638e+01, -9.31044534e+01,  9.90044896e+01,
         6.94862592e+01, -2.45383653e+02,  5.88147173e+01,  1.68960740e+01,
         3.17976062e+01,  9.13386293e+01, -7.29569849e+01,  2.12732755e+01,
        -1.49036736e+02, -1.04372017e+02, -1.13579090e+01, -3.80647498e+01,
        -9.87747122e+01, -7.58356917e+01, -1.76715965e+02, -1.79692755e+01,
         1.36816813e+02, -9.67400883e+01, -2.21825944e+02, -4.68294215e+01,
         6.38989019e+01, -1.62996285e+02, -6.35857289e+01, -1.74869522e+02,
        -1.75191008e+01, -1.38941763e+02, -1.16079917e+02,  6.02763301e+01,
        -3.84269944e+01,  6.73383359e+01, -8.38614235e+00, -3.02944271e+01,
         1.76667357e+01,  1.39281523e+02,  2.51809406e+02,  2.16664418e+00,
        -2.76630000e+02,  1.39282832e+02, -5.40968303e+01, -1.13352382e+02,
         4.20054889e+01, -1.13944609e+02,  1.84926781e+02, -1.16933237e+02,
         4.03200565e+01, -3.48195018e+01, -3.62100677e+01, -7.26723501e+01,
        -1.04290223e+02,  9.65271811e+01, -1.95217623e+02,  1.22943381e+02,
        -5.94391533e+01,  5.55938936e+00, -2.82227425e+01,  4.92126753e+01,
        -1.98852233e+02,  1.12302040e+02, -4.66263515e+01, -1.85087415e+02,
         2.26802447e+02,  1.12112468e+02,  8.14734953e+01, -5.87979816e+01,
        -1.14255995e+02,  2.44374149e+02, -8.89908615e+01, -1.33566195e+02,
         1.81247374e+02, -2.62429888e+02,  4.19575873e+01,  1.99064003e+01,
         7.81451782e+01,  2.24961508e+00,  7.96316914e+01, -7.70445473e+01,
         3.00563003e+01, -2.09405300e+02, -2.02196198e+02,  4.18705386e+01,
         4.54908060e+01,  2.30375365e+01, -1.46181548e+01,  8.63927647e+01,
        -1.06509430e+02, -2.69164447e+01,  1.44092298e+00,  1.31414689e+02,
        -1.16353986e+01,  5.73292534e+00, -1.10849955e+02, -9.70101677e+01,
         3.12605570e+01, -6.56135105e+01,  2.25980690e+01, -1.58544853e+01,
         1.83440841e+01,  1.95554060e+02, -1.56130035e+02,  1.14394428e+02,
        -1.46744328e+01,  8.64276131e+00, -2.17974471e+00, -2.27595706e+02,
         5.51062877e+00, -1.26042370e+01, -5.77215210e+01,  2.36159846e+01,
         1.96616159e+01,  1.33165660e+01,  6.10931194e+01,  1.26011831e+02,
        -8.24625901e+01, -1.71645644e+02,  1.35553743e+02, -3.92507861e+01,
        -8.77716955e+01,  1.20630151e+01, -2.39465879e+02,  6.86392783e+01,
        -1.06395166e+01,  2.59705842e+01,  1.72852101e+01, -1.38103567e+02,
         1.61260513e+02,  2.02556702e+02,  4.06578501e+01,  8.39934007e+01,
        -9.24702144e+01, -9.20953223e+01,  3.76422657e+01, -1.88466625e+01,
         7.15279879e+01, -1.72726637e+01, -1.09759526e+02,  8.79650464e+01,
         1.68588223e+02,  2.38358957e+01, -6.15506464e+01, -9.24821527e+01,
         3.69059744e+01, -9.12045264e+01,  1.23256374e+02, -1.06335784e+02,
         9.60353053e+01, -9.82785967e+01,  6.93941477e+01,  1.38542888e+02,
         1.52106117e+02,  1.39874679e+02, -1.48065651e+02, -6.61132809e+01,
        -1.72672018e+01, -2.68634212e+01,  1.61500079e+02, -1.93372035e+02,
        -5.84327327e+01, -6.24813389e+01,  1.41165203e+02, -4.37871521e+01,
         5.71514363e+01,  5.28075005e+01,  5.32886023e+01, -1.39110686e+02,
        -9.01795095e+01, -4.22925907e+00,  9.46959487e+01,  1.85781999e+01,
         5.74049351e+01, -1.42743757e+02, -5.49111647e+01, -5.56237060e-01,
         1.28582886e+02, -1.78274205e+02, -1.85211599e+02,  1.11320028e+02,
         5.82479847e+01, -1.10911516e+01, -8.38452263e+01,  1.43426746e+01,
        -6.56027146e+01, -2.19296503e+02, -8.38376669e+01, -7.17066345e+01,
        -1.02719000e+02, -6.12282267e+00, -9.83466061e+01, -1.71491422e+02,
        -1.82559240e+02, -6.03566116e+01, -1.24077740e+02, -1.86767254e+01,
         1.47824719e+02, -1.63907559e+02,  5.27658736e+01, -1.13860958e+02,
        -1.01636147e+02,  9.03689432e+01,  1.87471056e+00, -4.95206985e+00,
         4.67901600e+01, -9.12067697e+01,  1.95842677e+02,  1.71526432e+02,
        -1.35878995e+02, -7.95342943e+01, -8.98676308e+01,  2.85209730e+02,
        -1.33197955e+01,  1.44401579e+02, -2.01830284e+01, -1.25132766e+01,
         1.86073347e+02,  5.71446620e+01,  1.15696190e+02,  1.06381358e+02,
         1.20378005e+02, -5.83373339e+01, -2.10794367e+02, -1.69372518e+02,
        -9.32140738e+01,  2.14264247e+02, -8.00698014e+01,  7.51565713e+01,
         4.90216316e+01, -1.26711794e+02, -1.20611648e+02, -1.40591772e+01,
         7.33410450e+01,  8.85988163e+01,  2.12679641e+02, -2.29811863e+01,
        -9.36861385e+01,  5.52472252e+01, -3.05417605e+01, -2.81029191e+02,
        -6.53160472e-01,  1.66082222e+02,  1.91664337e+02, -2.39800394e+02,
         1.89918708e+02,  1.60585369e+01,  1.59406411e+02,  1.48313466e+02,
        -2.28431168e+01,  9.02989948e+00,  4.14225833e+01, -4.10470604e+01,
         5.53877317e+01, -1.11983838e+02, -8.64781195e+01,  6.40193122e+01,
         2.98070298e+02,  2.97743494e+01, -1.71934905e+02, -9.84611611e+01,
         5.53074841e+01,  1.74636538e+01, -1.11253320e+02,  6.28684586e+01,
         9.99899077e+00,  1.53509215e+01, -1.65485293e+02,  1.18489629e+02,
         2.66880395e+01,  1.58084766e+02, -8.32994458e+00,  6.66904120e+01,
         1.75063854e+02, -6.55566281e+01, -5.43579080e+01, -6.29112332e+01,
         6.40191350e+01, -3.50679495e+01, -1.82945092e+00, -6.18032378e+01,
        -4.57085667e+01,  6.55212256e+01,  6.43854660e+01,  7.74034372e+01,
         1.67508902e+02,  3.73370700e+01,  1.00151596e+01, -2.01098767e+01,
        -1.00899200e+02, -1.09109358e+02, -2.10924084e+02, -7.56825113e+00,
        -1.52283099e+02,  1.04652318e+02,  2.11521758e+02,  1.21246828e+02,
         2.78647976e+01,  2.13151302e+02,  3.84419853e+01,  9.64879934e+01,
        -7.38183520e+01,  1.93334919e+02, -1.04281807e+02, -8.80663922e+01,
         1.29018602e+02,  4.79873913e+01,  1.28337271e+01, -4.77022325e+01,
         1.49780434e+02,  1.15433002e+02,  4.54240594e+01,  4.63911298e+01,
         1.45833160e+01,  1.15892648e+02,  1.15762803e+02,  4.44225045e+01,
        -1.94671888e+02,  5.74534873e+01,  1.80727119e+02,  8.61416910e+01,
        -2.45485277e+01, -6.60354331e+01, -1.70751615e+02,  6.96257303e+01,
        -1.72395823e+02,  8.67877365e+01, -7.06483291e+01,  6.23105577e+00,
         1.18034073e+02,  9.37679184e+00,  1.41176898e+02,  1.41085370e+01,
        -1.59847541e+02, -5.95199355e+01,  2.31196192e+02, -1.29491517e+02]))

In [34]:
x = data[0]  # for to get features
y = data[1]  # for to get labels

In [35]:
x.shape

(1000, 3)

In [36]:
x

array([[ 0.14000933, -0.05431813,  0.17998741],
       [ 1.10182046, -0.87081727, -1.00542591],
       [ 0.2517129 ,  0.52562564, -0.70334619],
       ...,
       [ 0.62277559, -0.37504158, -1.27352294],
       [ 2.18771222, -0.70100731,  1.96876179],
       [-0.51319481, -1.11554337, -0.49791755]])

In [37]:
y

array([ 1.76521073e+01, -3.86626127e+01,  2.69869840e+00,  3.83737933e+01,
       -5.90274571e+01, -7.30768595e+01,  1.12083058e+02, -7.05306383e+01,
        2.32833470e+00, -2.21662380e+01,  7.58491375e+01, -1.62193316e+02,
       -1.58353923e+01, -1.32012268e+02, -6.46348381e+01, -7.58868405e+00,
        9.74578756e+01,  1.04645046e+02, -2.74244836e+01,  2.54646726e+01,
       -7.77558058e+01, -1.81852095e+02,  1.38926347e+02,  5.00482784e+01,
        6.74253839e+01,  2.07384154e+02,  2.75955808e+01,  4.93479467e+01,
        4.35423796e+01, -1.53903959e+02,  2.46444558e+01, -2.49105558e+01,
       -1.24680342e+02, -1.83518717e+01,  1.23756131e+02, -6.99284014e+00,
       -5.20616339e+01,  1.03207366e+02,  1.44530183e+01, -7.81259985e+01,
       -1.77530755e+02, -3.44155415e+01, -5.34576019e+01,  1.35698585e+02,
       -1.12700214e+02, -3.71827948e+01, -2.43786216e+01, -1.44762021e+02,
       -1.31599841e+02,  2.24253971e+02,  1.05071186e+02, -3.01923846e+01,
       -6.93869013e+01,  1.79460403e+01,  4.22585640e+01, -3.23054100e+01,
        9.13398741e+01,  1.47756423e+01,  5.56348570e+01, -1.61094419e+02,
       -7.85477525e+01,  1.84077107e+02,  1.18643234e+02,  2.14827312e+01,
       -5.60436957e+01,  1.51890881e+02,  1.23109978e+02,  3.55768661e+01,
       -1.35099777e+02,  2.43753645e+01,  2.42860907e+02, -2.23396689e+02,
       -6.90004844e+01,  1.89772712e+02, -1.55378915e+02,  8.39761266e+01,
        2.56946563e+01, -5.75553527e+01, -5.76038168e+01,  2.22461500e+01,
       -2.29138312e+01, -5.26080733e+01,  7.71908413e+01, -9.14835855e+01,
       -1.90478988e+02, -4.44331435e+01,  2.69155413e+01,  4.06399224e+01,
        9.47282150e-01, -3.65829659e+01, -1.74752167e+01, -6.10359030e+01,
        1.18214797e+01, -1.71376536e+02,  1.18957234e+02, -4.42701800e+01,
        7.27169045e+01, -2.68259622e+02, -2.04132160e+02, -5.70307865e+01,
        2.44059475e+02,  9.48450081e+01,  1.48678108e+02, -9.98404865e+01,
        1.23815207e+02, -7.33122978e+01, -6.78417151e+01, -8.62477491e+01,
        3.94496030e+01, -3.02669440e+01,  9.32546938e+01, -1.81772598e+00,
       -1.40815363e+02, -1.64711386e+02, -8.21125242e+01, -9.06320124e+01,
       -1.08776224e+01,  2.24837123e+01, -1.81578137e+02,  7.64969181e+01,
        1.62306259e+00, -1.78076235e+02, -1.46201344e+02,  9.36053832e+01,
        2.11356607e+02, -2.48587994e+00,  2.91576253e+01,  7.67135923e+01,
       -1.89179356e+01,  7.80446912e+01, -3.63095267e+01, -6.64944420e+01,
       -1.75102826e+01, -5.56556908e+01, -1.21727046e+02, -9.83989970e+01,
       -1.31825557e+02, -3.54906068e+01, -7.15556003e+01,  7.26966050e+01,
        7.71960590e+01, -6.25076351e+01, -6.03436824e+01, -2.04665355e+02,
       -3.07357264e+01,  1.80853606e+02,  8.95785336e+01, -2.36998882e+01,
       -5.42645518e+00,  1.19893403e+02, -1.46415456e+01, -8.12355385e+01,
       -6.60328995e+01,  7.41949864e+01, -1.01988297e+02, -1.75919276e+02,
        1.91695669e+02, -7.63289468e+01, -1.16206919e+02, -1.57342442e+02,
        1.95012530e+02, -9.82502811e+01, -1.12173567e+02,  1.30647112e+02,
       -4.92908871e+00,  9.04348666e+01,  3.11950711e+01,  3.98746562e+01,
       -7.50169198e+01, -1.19110154e+01, -2.11614020e+02,  1.71632695e+01,
        1.57492478e+01,  9.64643191e+01,  2.11997324e+02, -1.04053028e+01,
        1.72757856e+02,  6.31134545e+01, -7.06290120e+01, -2.44023055e+01,
       -1.11367435e+02, -3.41521628e+01, -5.73368236e+01, -9.84922231e+01,
       -1.56361708e+02, -1.03670666e+02, -8.59351805e+00,  7.37759707e+01,
        9.59563166e+01,  7.59438600e+01,  1.80036641e+01,  6.76790065e+01,
        5.90822196e+01,  6.08902379e+01,  7.87882383e+01, -1.92035020e+02,
       -9.53674296e+01, -9.35111573e+01,  3.87918259e+01, -2.31058990e+02,
       -1.31708715e+02, -1.69107013e+02, -1.05103748e+02,  2.44180162e+02,
       -2.29926853e+01, -1.42100535e+02,  3.48942153e+01,  2.13360253e+02,
        9.26202523e+01,  9.76296929e+01, -1.17310693e+01, -8.46131912e+01,
        1.28864087e+02, -1.36834932e+02, -1.19167350e+02,  1.90171432e+02,
        5.53546928e+01, -1.43800503e+02,  1.00074543e+02, -3.30647622e+00,
       -7.33577420e+01,  1.15699654e+02,  2.23191567e+02,  1.42304385e+02,
        3.51385987e+01,  1.30307417e+02, -2.78193575e+01,  2.01610677e+02,
       -1.82972810e+02, -1.96011755e+01,  2.73150593e-01, -5.21350306e+01,
       -1.00557686e+02, -2.10693381e+02, -9.93966243e+00,  1.54460738e+01,
        5.31408493e+01, -3.58388634e+01, -5.70706963e+01, -6.58420108e+01,
        3.84246312e+01, -9.49989625e+01, -4.96825176e+01,  6.33462289e+01,
        9.86010102e+01,  6.28701524e+01,  3.32334192e+02, -7.97989594e+01,
       -1.08225282e+02, -1.85890928e+02,  2.16602416e+01, -1.01501257e+02,
        1.05326463e+02, -4.11750605e+01,  1.61680297e+02,  1.45833945e+02,
        1.90237877e+01, -1.89752067e+02,  3.11037289e+01, -1.15322632e+01,
        1.40886695e+02, -7.45229054e+01, -1.59343443e+02, -4.80576633e+00,
        8.34521888e+01,  8.42290253e+01, -6.80439221e+01,  9.12077404e+01,
       -1.52354571e+01, -8.40260084e+01,  6.09544159e+01,  2.02106504e+01,
       -8.11963358e+01, -7.29430069e+01,  2.11201519e+02,  2.66641431e+01,
        5.54440985e+01,  5.04286700e+00,  1.37736791e+02,  8.36839241e+01,
        1.35742811e+01, -1.36363956e+02,  1.40213301e+01,  1.18760601e+02,
        8.04841232e+00, -1.48423396e+01, -3.53365267e+01,  2.34178639e+01,
       -7.84102194e+01,  6.97079536e+01,  5.16658259e+01,  1.10859269e+02,
        1.39686913e+02, -1.68369384e+02, -1.90676812e+02,  1.30537798e+02,
        1.23175765e+02, -2.02991566e+02, -1.65889951e+02, -1.59824085e+02,
        8.24174380e+01, -1.04772047e+02,  1.28202862e+02,  7.39516882e+01,
        1.15207156e+01, -3.93132074e+01, -4.08600913e+01,  1.07403050e+02,
        2.17571350e+01,  1.12405671e+02,  6.03088988e+01, -5.19047001e+00,
        8.84453402e+00,  9.40450324e+01,  1.61645770e+02,  5.04671336e+01,
        4.92910814e+01, -9.65575601e+01, -1.57360831e+02,  1.03964036e+02,
        1.45632566e+02, -4.38547833e+01, -6.98433640e+01, -3.99559562e+01,
       -1.48062379e+02,  8.50609870e+01,  9.43912773e+01, -1.58150383e+02,
       -1.54422942e+02, -9.89359481e+01,  1.04772562e+02,  2.61467512e+01,
       -1.06882349e+02, -2.98308160e+01,  7.90714115e+01, -6.58121292e+01,
        2.80867865e+01,  6.71264438e+01, -5.18521802e+01, -4.36268296e+01,
        3.72060436e+01,  9.75401233e+01,  2.77964137e+02, -2.80254139e+00,
        5.42728622e+01, -5.20969522e+01,  8.60793231e+01, -1.36767704e+00,
        8.15381413e+01, -7.16276541e+01, -1.42808538e+00,  1.92849018e+01,
       -3.09188359e+01, -1.22370274e+02,  1.53826210e+02, -1.35348987e+02,
       -2.31386034e+02,  2.37492858e+01,  5.01517961e+01, -6.40315969e+01,
        1.39778178e+02,  1.64172843e+02, -6.86716679e+01,  9.70055802e+01,
       -6.15824707e+00,  5.72792522e+01,  7.43971182e+01,  3.01271419e+01,
       -1.98405299e+00, -4.12896035e+01, -2.33778661e+01,  1.61463978e+01,
        3.44890855e+01, -3.34580218e+02, -8.53128481e+01,  7.83005598e+01,
       -1.24924157e+02,  2.40165588e+02, -1.01624486e+02, -1.30430616e+02,
        2.76639820e+01, -5.88354103e+01, -1.27297303e+01,  1.39514391e+02,
       -2.44912658e+01,  4.64456269e+00, -3.73663089e+01, -7.24580027e+01,
        1.43218676e+02,  8.78040857e+01,  3.49200438e+00, -1.80725500e+02,
       -3.66808637e+01,  1.17778604e+02,  1.62304140e+02, -1.49864681e+02,
        4.74856132e+01, -6.07922708e+01, -4.45400888e+01,  3.46265814e+01,
       -1.21527352e+02,  2.83053945e+00,  2.71925812e+02, -2.16245347e+01,
       -1.04242270e+02,  3.70438349e+01, -8.83271842e+01,  3.05844546e+02,
       -2.01391492e+02, -8.24444006e+01, -1.33124048e+02,  2.25155520e+01,
       -3.08645378e+02,  1.03074965e+02,  1.73389723e+02,  8.10767655e+00,
       -1.05892974e+02, -8.04781625e+01, -1.39558361e+02, -3.68576369e+01,
       -1.39879020e+02,  7.84358407e+01,  1.34929917e+01, -2.26094475e+02,
        8.77523397e+01,  6.06072961e-01, -9.43487218e+00,  3.54422137e+01,
       -1.03136451e+02,  1.28587222e+02,  3.42547584e+01,  4.15429792e-01,
        1.56706946e+02,  1.07537869e+02, -5.22151933e+01,  1.46660939e+02,
        2.35253481e+02,  1.43090195e+02, -2.87559807e+02, -3.70331299e+01,
        1.43089783e+02,  1.37472759e+02, -1.63302609e+02,  5.32961148e+01,
       -1.31334189e+02,  1.84627871e+01,  1.81216196e+02, -3.30323496e+01,
        2.00999262e+00,  3.60310751e+01,  1.18151977e+01,  8.01899747e+01,
       -1.11077387e+02, -1.40174093e+01, -4.10849402e+01,  2.95236366e+01,
        1.04858476e+02, -5.04635345e+01,  1.60194230e+02,  3.59643559e+01,
       -1.56941937e+01,  3.04696211e+00,  1.14288322e+02, -2.30183516e+02,
       -9.16773628e+01, -1.60851265e+01, -9.47450456e+01, -1.31943251e+02,
        8.46202155e+01,  2.04178461e+02, -1.14579356e+02, -2.01135373e+02,
        2.92769872e+00, -1.03325133e+02, -6.77010155e+01,  9.44434198e-01,
       -8.85140140e+01,  1.55887707e+02,  6.43485302e+01, -3.10281318e+01,
        7.97747618e+01, -9.58903472e+01, -1.10294659e+02,  1.88269258e+01,
        1.59647256e+02, -6.69435157e+01,  2.85752131e+00, -1.11777655e+01,
       -1.08779465e+02,  3.43325086e+01, -5.74021433e+01,  1.19685285e+02,
        1.47935325e+01, -1.92339805e+01, -1.47381428e+02,  1.29230509e+02,
        1.00657697e+02, -1.76474345e+00,  9.36248837e+01,  2.89029989e+00,
       -1.00512371e+02, -6.88913924e+01,  2.51039419e+01,  4.91180226e+01,
        1.02459874e+02, -4.41068756e+01, -1.05746393e+02,  5.23648998e+01,
        1.84754241e+00, -2.18950081e+02,  1.38032299e+01,  7.33674869e+01,
       -6.15957818e+01, -8.76941672e+00,  2.74494904e+02,  1.82246579e+02,
        3.00885747e+02, -1.30018792e+02,  2.44297785e+02, -1.14798267e+01,
       -1.25200617e+02,  2.12059346e+02,  1.91418517e+01, -7.11527284e+01,
       -5.44465212e+01,  2.22071817e+01, -3.22047074e+01, -2.52804369e+02,
        1.68366382e+02, -2.53882644e+01, -1.20574901e+02, -5.08674068e+01,
       -8.53323850e+01, -1.05395653e+01, -1.44961617e+02,  1.79455278e+01,
        1.00285806e+02,  5.99629052e+01,  1.77239328e+02, -1.48244718e+02,
       -6.34092852e+01,  3.87737324e+00, -1.50137675e+02,  2.11842614e+01,
        2.06431518e+02, -2.39372993e+02,  1.01046621e+02,  1.56466796e+01,
       -1.30142637e+02,  7.25762682e-01,  2.20743852e+01,  9.92435383e+01,
       -4.94019759e+01, -4.92240471e+01,  3.07894945e+01,  5.65610319e+01,
       -8.31896042e+00,  7.02102363e+00, -1.47457466e+01,  1.90560172e+02,
        2.21469308e+02,  2.42604693e+02, -1.06895510e+02, -5.16028829e+01,
       -6.52224514e+01,  2.12797475e+02,  1.15548290e+02, -3.78658464e+00,
        3.71151517e+01, -1.48413499e+02, -1.67614583e+02, -9.53227077e+01,
       -1.28677354e+02, -1.31291051e+02,  2.48106103e+01,  6.57594905e+01,
        1.37624098e+02,  8.00834154e+01, -8.52550134e+01, -1.24013667e+02,
        5.15528559e+01, -2.25230746e+02,  5.27977185e+01, -9.29342462e+01,
       -8.05163729e+01,  1.15400400e+02, -1.18224137e+02,  1.56853899e+02,
        1.67821841e+01,  4.87690049e+01, -6.55958902e+01, -4.20464414e+01,
        7.05450785e+01,  7.97659458e+01,  1.07433406e+02,  1.46863176e+02,
       -1.89001302e+01, -1.17866673e+02,  2.42607702e+01, -1.79419786e+01,
        7.86027339e+01,  7.87249293e+01,  4.02496730e+01,  1.33054845e+02,
        3.32788685e+01, -1.14441344e+02,  8.98620947e+01,  1.64498539e+02,
       -4.80201176e+01, -6.87907224e+01, -1.77165614e+01, -1.84425093e+01,
        1.41115853e+02,  1.44515773e+02, -1.79787469e+01, -5.59164608e+01,
        1.22403001e+02, -8.31147867e+01,  6.26969337e+01,  1.39560766e+02,
        4.69729013e+01, -6.71660764e+00, -1.46257455e+02, -2.55245193e+01,
       -1.71359269e+01,  1.45654729e+00, -2.47458031e+02,  1.06187384e+02,
       -1.11110427e+02, -3.94882872e+01,  2.70043384e+02, -3.01304895e+01,
       -2.30824555e+01, -1.52445401e+02,  1.21093800e+02, -4.58604669e+00,
       -1.47525614e+02,  1.65114896e+02,  4.29322426e+01, -6.38611204e+00,
       -1.04899009e+02,  2.73262972e+01, -2.77725251e+01,  4.43080220e+00,
        1.69550016e+02, -1.40579055e+01,  1.50159743e+02,  1.33392827e+02,
       -4.83972958e+01, -1.28120147e+02,  1.04473963e+02, -5.14183875e+01,
        3.06720133e+01,  1.18728032e+02,  8.27160553e+01, -9.12618882e+01,
        4.64589269e+00, -1.34759167e+02,  7.66330808e+01,  7.03551243e+01,
       -5.22644919e+01, -1.87166713e+02,  5.06333766e+01, -9.88541668e+00,
       -1.88141573e+02,  3.38152638e+01, -9.31044534e+01,  9.90044896e+01,
        6.94862592e+01, -2.45383653e+02,  5.88147173e+01,  1.68960740e+01,
        3.17976062e+01,  9.13386293e+01, -7.29569849e+01,  2.12732755e+01,
       -1.49036736e+02, -1.04372017e+02, -1.13579090e+01, -3.80647498e+01,
       -9.87747122e+01, -7.58356917e+01, -1.76715965e+02, -1.79692755e+01,
        1.36816813e+02, -9.67400883e+01, -2.21825944e+02, -4.68294215e+01,
        6.38989019e+01, -1.62996285e+02, -6.35857289e+01, -1.74869522e+02,
       -1.75191008e+01, -1.38941763e+02, -1.16079917e+02,  6.02763301e+01,
       -3.84269944e+01,  6.73383359e+01, -8.38614235e+00, -3.02944271e+01,
        1.76667357e+01,  1.39281523e+02,  2.51809406e+02,  2.16664418e+00,
       -2.76630000e+02,  1.39282832e+02, -5.40968303e+01, -1.13352382e+02,
        4.20054889e+01, -1.13944609e+02,  1.84926781e+02, -1.16933237e+02,
        4.03200565e+01, -3.48195018e+01, -3.62100677e+01, -7.26723501e+01,
       -1.04290223e+02,  9.65271811e+01, -1.95217623e+02,  1.22943381e+02,
       -5.94391533e+01,  5.55938936e+00, -2.82227425e+01,  4.92126753e+01,
       -1.98852233e+02,  1.12302040e+02, -4.66263515e+01, -1.85087415e+02,
        2.26802447e+02,  1.12112468e+02,  8.14734953e+01, -5.87979816e+01,
       -1.14255995e+02,  2.44374149e+02, -8.89908615e+01, -1.33566195e+02,
        1.81247374e+02, -2.62429888e+02,  4.19575873e+01,  1.99064003e+01,
        7.81451782e+01,  2.24961508e+00,  7.96316914e+01, -7.70445473e+01,
        3.00563003e+01, -2.09405300e+02, -2.02196198e+02,  4.18705386e+01,
        4.54908060e+01,  2.30375365e+01, -1.46181548e+01,  8.63927647e+01,
       -1.06509430e+02, -2.69164447e+01,  1.44092298e+00,  1.31414689e+02,
       -1.16353986e+01,  5.73292534e+00, -1.10849955e+02, -9.70101677e+01,
        3.12605570e+01, -6.56135105e+01,  2.25980690e+01, -1.58544853e+01,
        1.83440841e+01,  1.95554060e+02, -1.56130035e+02,  1.14394428e+02,
       -1.46744328e+01,  8.64276131e+00, -2.17974471e+00, -2.27595706e+02,
        5.51062877e+00, -1.26042370e+01, -5.77215210e+01,  2.36159846e+01,
        1.96616159e+01,  1.33165660e+01,  6.10931194e+01,  1.26011831e+02,
       -8.24625901e+01, -1.71645644e+02,  1.35553743e+02, -3.92507861e+01,
       -8.77716955e+01,  1.20630151e+01, -2.39465879e+02,  6.86392783e+01,
       -1.06395166e+01,  2.59705842e+01,  1.72852101e+01, -1.38103567e+02,
        1.61260513e+02,  2.02556702e+02,  4.06578501e+01,  8.39934007e+01,
       -9.24702144e+01, -9.20953223e+01,  3.76422657e+01, -1.88466625e+01,
        7.15279879e+01, -1.72726637e+01, -1.09759526e+02,  8.79650464e+01,
        1.68588223e+02,  2.38358957e+01, -6.15506464e+01, -9.24821527e+01,
        3.69059744e+01, -9.12045264e+01,  1.23256374e+02, -1.06335784e+02,
        9.60353053e+01, -9.82785967e+01,  6.93941477e+01,  1.38542888e+02,
        1.52106117e+02,  1.39874679e+02, -1.48065651e+02, -6.61132809e+01,
       -1.72672018e+01, -2.68634212e+01,  1.61500079e+02, -1.93372035e+02,
       -5.84327327e+01, -6.24813389e+01,  1.41165203e+02, -4.37871521e+01,
        5.71514363e+01,  5.28075005e+01,  5.32886023e+01, -1.39110686e+02,
       -9.01795095e+01, -4.22925907e+00,  9.46959487e+01,  1.85781999e+01,
        5.74049351e+01, -1.42743757e+02, -5.49111647e+01, -5.56237060e-01,
        1.28582886e+02, -1.78274205e+02, -1.85211599e+02,  1.11320028e+02,
        5.82479847e+01, -1.10911516e+01, -8.38452263e+01,  1.43426746e+01,
       -6.56027146e+01, -2.19296503e+02, -8.38376669e+01, -7.17066345e+01,
       -1.02719000e+02, -6.12282267e+00, -9.83466061e+01, -1.71491422e+02,
       -1.82559240e+02, -6.03566116e+01, -1.24077740e+02, -1.86767254e+01,
        1.47824719e+02, -1.63907559e+02,  5.27658736e+01, -1.13860958e+02,
       -1.01636147e+02,  9.03689432e+01,  1.87471056e+00, -4.95206985e+00,
        4.67901600e+01, -9.12067697e+01,  1.95842677e+02,  1.71526432e+02,
       -1.35878995e+02, -7.95342943e+01, -8.98676308e+01,  2.85209730e+02,
       -1.33197955e+01,  1.44401579e+02, -2.01830284e+01, -1.25132766e+01,
        1.86073347e+02,  5.71446620e+01,  1.15696190e+02,  1.06381358e+02,
        1.20378005e+02, -5.83373339e+01, -2.10794367e+02, -1.69372518e+02,
       -9.32140738e+01,  2.14264247e+02, -8.00698014e+01,  7.51565713e+01,
        4.90216316e+01, -1.26711794e+02, -1.20611648e+02, -1.40591772e+01,
        7.33410450e+01,  8.85988163e+01,  2.12679641e+02, -2.29811863e+01,
       -9.36861385e+01,  5.52472252e+01, -3.05417605e+01, -2.81029191e+02,
       -6.53160472e-01,  1.66082222e+02,  1.91664337e+02, -2.39800394e+02,
        1.89918708e+02,  1.60585369e+01,  1.59406411e+02,  1.48313466e+02,
       -2.28431168e+01,  9.02989948e+00,  4.14225833e+01, -4.10470604e+01,
        5.53877317e+01, -1.11983838e+02, -8.64781195e+01,  6.40193122e+01,
        2.98070298e+02,  2.97743494e+01, -1.71934905e+02, -9.84611611e+01,
        5.53074841e+01,  1.74636538e+01, -1.11253320e+02,  6.28684586e+01,
        9.99899077e+00,  1.53509215e+01, -1.65485293e+02,  1.18489629e+02,
        2.66880395e+01,  1.58084766e+02, -8.32994458e+00,  6.66904120e+01,
        1.75063854e+02, -6.55566281e+01, -5.43579080e+01, -6.29112332e+01,
        6.40191350e+01, -3.50679495e+01, -1.82945092e+00, -6.18032378e+01,
       -4.57085667e+01,  6.55212256e+01,  6.43854660e+01,  7.74034372e+01,
        1.67508902e+02,  3.73370700e+01,  1.00151596e+01, -2.01098767e+01,
       -1.00899200e+02, -1.09109358e+02, -2.10924084e+02, -7.56825113e+00,
       -1.52283099e+02,  1.04652318e+02,  2.11521758e+02,  1.21246828e+02,
        2.78647976e+01,  2.13151302e+02,  3.84419853e+01,  9.64879934e+01,
       -7.38183520e+01,  1.93334919e+02, -1.04281807e+02, -8.80663922e+01,
        1.29018602e+02,  4.79873913e+01,  1.28337271e+01, -4.77022325e+01,
        1.49780434e+02,  1.15433002e+02,  4.54240594e+01,  4.63911298e+01,
        1.45833160e+01,  1.15892648e+02,  1.15762803e+02,  4.44225045e+01,
       -1.94671888e+02,  5.74534873e+01,  1.80727119e+02,  8.61416910e+01,
       -2.45485277e+01, -6.60354331e+01, -1.70751615e+02,  6.96257303e+01,
       -1.72395823e+02,  8.67877365e+01, -7.06483291e+01,  6.23105577e+00,
        1.18034073e+02,  9.37679184e+00,  1.41176898e+02,  1.41085370e+01,
       -1.59847541e+02, -5.95199355e+01,  2.31196192e+02, -1.29491517e+02])

# ASSIGNING NAME TO FEATURES WITH COLUMN NAME RESEARCH, SALARIES, INFRASTRUCTURE AND EXPENDATURE

In [38]:
df = pd.DataFrame(x, columns=['Research', 'Salaries', 'Infrastructure'])

# Now apply np.interp to the 'Research' column of the DataFrame
df['Research'] = np.interp(df['Research'], (df['Research'].min(), df['Research'].max()), (0, 2000))

# If you also intended to apply this to other columns, you can do so similarly:
df['Salaries'] = np.interp(df['Salaries'], (df['Salaries'].min(), df['Salaries'].max()), (0, 2000))
df['Infrastructure'] = np.interp(df['Infrastructure'], (df['Infrastructure'].min(), df['Infrastructure'].max()), (0, 2000))

In [39]:
y = pd.DataFrame(y, columns=['Expenditure'])
y['Expenditure'] = np.interp(y['Expenditure'], (y['Expenditure'].min(), y['Expenditure'].max()), (6000, 20000))
y

      Expenditure
0    13394.131068
1    12211.961260
2    13080.226132
3    13829.124824
4    11784.458393
..            ...
995  13319.743735
996   9668.023119
997  11774.120187
998  17876.890980
999  10305.262829

[1000 rows x 1 columns]

In [40]:

y['Expenditure'] = np.interp(y['Expenditure'], (y['Expenditure'].min(), y['Expenditure'].max()), (6000, 20000))
y

      Expenditure
0    13394.131068
1    12211.961260
2    13080.226132
3    13829.124824
4    11784.458393
..            ...
995  13319.743735
996   9668.023119
997  11774.120187
998  17876.890980
999  10305.262829

[1000 rows x 1 columns]

In [41]:

y['Expenditure'] = np.interp(y['Expenditure'], (y['Expenditure'].min(), y['Expenditure'].max()), (6000, 20000))
y

      Expenditure
0    13394.131068
1    12211.961260
2    13080.226132
3    13829.124824
4    11784.458393
..            ...
995  13319.743735
996   9668.023119
997  11774.120187
998  17876.890980
999  10305.262829

[1000 rows x 1 columns]

In [42]:
df

        Research     Salaries  Infrastructure
0    1083.562980  1106.057333      939.464166
1    1369.708726   850.000259      612.066507
2    1116.795598  1287.929792      695.497486
3    1157.412187   742.224603     1247.594322
4     911.237483   789.820093     1026.598749
..           ...          ...             ...
995  1455.502051  1170.402728      502.649126
996   568.956724   671.923193     1018.320393
997  1227.189423  1005.477304      538.021160
998  1692.769354   903.253275     1433.503277
999   889.230038   773.253272      752.234537

[1000 rows x 3 columns]

In [43]:
y = pd.DataFrame(y, columns=['Expenditure'])
y['Expenditure'] = np.interp(y['Expenditure'], (y['Expenditure'].min(), y['Expenditure'].max()), (6000, 20000))
y

      Expenditure
0    13394.131068
1    12211.961260
2    13080.226132
3    13829.124824
4    11784.458393
..            ...
995  13319.743735
996   9668.023119
997  11774.120187
998  17876.890980
999  10305.262829

[1000 rows x 1 columns]

In [44]:
df

        Research     Salaries  Infrastructure
0    1083.562980  1106.057333      939.464166
1    1369.708726   850.000259      612.066507
2    1116.795598  1287.929792      695.497486
3    1157.412187   742.224603     1247.594322
4     911.237483   789.820093     1026.598749
..           ...          ...             ...
995  1455.502051  1170.402728      502.649126
996   568.956724   671.923193     1018.320393
997  1227.189423  1005.477304      538.021160
998  1692.769354   903.253275     1433.503277
999   889.230038   773.253272      752.234537

[1000 rows x 3 columns]

# Spliting The Data Into Train And Test

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)
x_test.shape

(200, 3)

# Standarizing The Data

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)
x_test = x_test_scaled

In [47]:
x_train

array([[-1.02627367, -0.40052275, -0.85426657],
       [ 0.32453021,  1.1728171 , -1.04243009],
       [ 1.74240627, -0.41492711, -0.49229759],
       ...,
       [ 0.32576847,  1.07292361,  1.00404049],
       [ 2.18572341, -0.6700704 ,  0.57293897],
       [ 0.5969664 , -0.62592341,  2.21946126]])

# Linear Resgression

In [48]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

# Testing And Evaluating The Model

In [49]:
y_pred = lr.predict(x_test)

In [50]:
from sklearn import metrics
print('RMSE: ',np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R2: ',metrics.r2_score(y_test, y_pred))
print('MAE: ',metrics.mean_absolute_error(y_test, y_pred))
print('Accuracy: ', lr.score(x_test, y_test)*100)

RMSE:  1.6856350150965808e-12
R2:  1.0
MAE:  1.2141754268668592e-12
Accuracy:  100.0